name: First github action pipeline

run-name: Deployed by @${{github.actor}}

on:
    push:
        branches:
            - main
jobs:
    print-username:
        name: printing name
        runs-on: ubuntu-latest
        steps:
            - name: print name to standard output
              run: echo The username is Taiwo