name: First github action pipeline

run-name: Deployed by @${{github.actor}}

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            user_name:
                description: 'What is your user name?'
                type: string
                required: true
jobs:
    print-username:
        name: printing name
        runs-on: ubuntu-latest
        steps:
            - name: print name to standard output
              run: echo The username is ${{inputs.user_name}}
            - name: Inspect the github context
              run: echo '${{github}}'